// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/item": {
            "post": {
                "description": "Create new item endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item"
                ],
                "summary": "Create item",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpmodels.CreateItemRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "[INCORRECT_REQUEST_BODY], [VALIDATION_FAILED]",
                        "schema": {
                            "$ref": "#/definitions/httpmodels.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpmodels.CreateItemRequest": {
            "type": "object",
            "required": [
                "Description",
                "MinBuyPrice",
                "Name",
                "Pictures",
                "SoldPrice"
            ],
            "properties": {
                "Description": {
                    "type": "string"
                },
                "MinBuyPrice": {
                    "type": "integer"
                },
                "Name": {
                    "type": "string"
                },
                "Pictures": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "SoldPrice": {
                    "type": "integer"
                }
            }
        },
        "httpmodels.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "AuthServiceAPI",
	Description:      "My first project.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
