// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/items": {
            "post": {
                "description": "Create new item endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item"
                ],
                "summary": "Create item",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpmodels.CreateItemRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Message: INCORRECT_REQUEST_BODY, VALIDATION_FAILED",
                        "schema": {
                            "$ref": "#/definitions/httpmodels.Error"
                        }
                    }
                }
            }
        },
        "/items/all": {
            "get": {
                "description": "Returns all items of current user user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item"
                ],
                "summary": "Returns all items",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/items/{id}": {
            "get": {
                "description": "Returns item by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item"
                ],
                "summary": "Returns item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Message: INCORRECT_PARAMETER",
                        "schema": {
                            "$ref": "#/definitions/httpmodels.Error"
                        }
                    }
                }
            },
            "put": {
                "description": "Update item by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item"
                ],
                "summary": "Update item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpmodels.CreateItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Message: INCORRECT_REQUEST_BODY, VALIDATION_FAILED, INCAORRECT_PARAMETER",
                        "schema": {
                            "$ref": "#/definitions/httpmodels.Error"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete item by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item"
                ],
                "summary": "Delete item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Message: INCORRECT_PARAMETER",
                        "schema": {
                            "$ref": "#/definitions/httpmodels.Error"
                        }
                    }
                }
            }
        },
        "/refresh": {
            "post": {
                "description": "Refresh jwt token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh jwt token",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpmodels.RefreshJWTRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/httpmodels.RefreshJWTResponse"
                        }
                    },
                    "400": {
                        "description": "[INCORRECT_REQUEST_BODY]",
                        "schema": {
                            "$ref": "#/definitions/httpmodels.Error"
                        }
                    },
                    "500": {
                        "description": "[INTERNAL_SERVER_ERROR]",
                        "schema": {
                            "$ref": "#/definitions/httpmodels.Error"
                        }
                    }
                }
            }
        },
        "/signin": {
            "post": {
                "description": "Sign in user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Sign in user",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpmodels.SignInRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/httpmodels.SignInResponse"
                        }
                    },
                    "400": {
                        "description": "[INCORRECT_REQUEST_BODY]",
                        "schema": {
                            "$ref": "#/definitions/httpmodels.Error"
                        }
                    },
                    "500": {
                        "description": "[INTERNAL_SERVER_ERROR]",
                        "schema": {
                            "$ref": "#/definitions/httpmodels.Error"
                        }
                    }
                }
            }
        },
        "/signup": {
            "post": {
                "description": "Sign up user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Sign up user",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpmodels.SignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/httpmodels.SignUpResponse"
                        }
                    },
                    "400": {
                        "description": "[INCORRECT_REQUEST_BODY]",
                        "schema": {
                            "$ref": "#/definitions/httpmodels.Error"
                        }
                    },
                    "500": {
                        "description": "[INTERNAL_SERVER_ERROR]",
                        "schema": {
                            "$ref": "#/definitions/httpmodels.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpmodels.CreateItemRequest": {
            "type": "object",
            "required": [
                "Description",
                "MinBuyPrice",
                "Name",
                "Pictures",
                "SoldPrice"
            ],
            "properties": {
                "Description": {
                    "type": "string"
                },
                "MinBuyPrice": {
                    "type": "integer"
                },
                "Name": {
                    "type": "string"
                },
                "Pictures": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "SoldPrice": {
                    "type": "integer"
                }
            }
        },
        "httpmodels.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "httpmodels.RefreshJWTRequest": {
            "type": "object",
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "httpmodels.RefreshJWTResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "httpmodels.SignInRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "httpmodels.SignInResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "httpmodels.SignUpRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "httpmodels.SignUpResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "AuthServiceAPI",
	Description:      "My first project.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
