basePath: /
definitions:
  httpmodels.CreateItemRequest:
    properties:
      Description:
        type: string
      MinBuyPrice:
        type: integer
      Name:
        type: string
      Pictures:
        items:
          type: string
        type: array
      SoldPrice:
        type: integer
    required:
    - Description
    - MinBuyPrice
    - Name
    - Pictures
    - SoldPrice
    type: object
  httpmodels.Error:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
  description: My first project.
  termsOfService: http://swagger.io/terms/
  title: AuthServiceAPI
  version: "1.0"
paths:
  /item:
    post:
      consumes:
      - application/json
      description: Create new item endpoint
      parameters:
      - description: request body
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/httpmodels.CreateItemRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: '[INCORRECT_REQUEST_BODY], [VALIDATION_FAILED]'
          schema:
            $ref: '#/definitions/httpmodels.Error'
      summary: Create item
      tags:
      - Item
swagger: "2.0"
